cohortOverlaps_CO2AnalysisModules:
  analysisName: "Cohort Overlaps"
  icon: "braille"
  mod_analysisSettings_ui: CO2AnalysisModules::mod_analysisSettings_cohortOverlaps_ui
  mod_analysisSettings_server: CO2AnalysisModules::mod_analysisSettings_cohortOverlaps_server
  fct_executeAnalysis: CO2AnalysisModules::execute_CohortOverlaps
  url_visualiseResults: http://localhost:3838/co2analysis/?pathToResultsDatabase=
cohortDemographics_CO2AnalysisModules:
  analysisName: "Cohort Demographics"
  icon: "users"
  mod_analysisSettings_ui: CO2AnalysisModules::mod_analysisSettings_cohortDemographics_ui
  mod_analysisSettings_server: CO2AnalysisModules::mod_analysisSettings_cohortDemographics_server
  fct_executeAnalysis: CO2AnalysisModules::execute_CohortDemographics
  url_visualiseResults: http://localhost:3838/co2analysis/?pathToResultsDatabase=
codeWAS_CO2AnalysisModules:
  analysisName: "Code WAS"
  icon: "tasks"
  mod_analysisSettings_ui: CO2AnalysisModules::mod_analysisSettings_codeWAS_ui
  mod_analysisSettings_server: CO2AnalysisModules::mod_analysisSettings_codeWAS_server
  fct_executeAnalysis: CO2AnalysisModules::execute_CodeWAS
  url_visualiseResults: http://localhost:3838/co2analysis/?pathToResultsDatabase=
timeCodeWAS_CO2AnalysisModules:
  analysisName: "Time Code WAS"
  icon: "road"
  mod_analysisSettings_ui: CO2AnalysisModules::mod_analysisSettings_timeCodeWAS_ui
  mod_analysisSettings_server: CO2AnalysisModules::mod_analysisSettings_timeCodeWAS_server
  fct_executeAnalysis: CO2AnalysisModules::execute_timeCodeWAS
  url_visualiseResults: http://localhost:3838/co2analysis/?pathToResultsDatabase=
CohortDiagnostics_HadesAnalysisModules:
  analysisName: "CohortDiagnostics"
  icon: "stethoscope"
  mod_analysisSettings_ui: HadesAnalysisModules::mod_analysisSettings_CohortDiagnostics_ui
  mod_analysisSettings_server: HadesAnalysisModules::mod_analysisSettings_CohortDiagnostics_server
  fct_executeAnalysis: HadesAnalysisModules::execute_CohortDiagnostics
  url_visualiseResults: http://localhost:3837/hadesanalysis/?analysisType=CohortDiagnostics&pathToResultsDatabase=

