# EUNOMIA
E1:
  cohortTableHandler:
    database:
      databaseId: E1
      databaseName: GiBleed
      databaseDescription: Eunomia database GiBleed
    connection:
      connectionDetailsSettings:
          dbms: sqlite
          server: <pathToGiBleedEunomiaSqlite>
    cdm:
        cdmDatabaseSchema: main
        vocabularyDatabaseSchema: main
    cohortTable:
        cohortDatabaseSchema: main
        cohortTableName: co2_e1_<timestamp>
  atlasConfig:
    webapiurl: https://api.ohdsi.org/WebAPI
    sourcekey:
    resultsshchema:

# EUNOMIA 2
E2:
  cohortTableHandler:
    database:
      databaseId: E2
      databaseName: MIMIC
      databaseDescription: Eunomia database MIMIC
    connection:
      connectionDetailsSettings:
          dbms: sqlite
          server: <pathToMIMICEunomiaSqlite>
    cdm:
        cdmDatabaseSchema: main
        vocabularyDatabaseSchema: main
    cohortTable:
        cohortDatabaseSchema: main
        cohortTableName: co2_e2_<timestamp>
  atlasConfig:
    webapiurl: https://api.ohdsi.org/WebAPI
    sourcekey:
    resultsshchema:
